version: '3.9'
services:
  # nxapp: # use this if running app from the presisted image instead of building it from git src + Dockerfile. Also be sure to presist database data in the image and import it in Dockerfile.
    # image: devwl/nxapp:1.0 # <dockerhub-username>/<remote-imgname:tag>
    # ports:
    # - 3000:3000

  nxapp:
    build: . # Download src from GitHub, cd do dir where Dockerfile is placed. Build the image.
    ports:
      - 3000:3000

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo-data:
    driver: local
